<?php
echo "<!DOCTYPE html>\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title>O'Connor Plumbing and Heating, Dublin &amp; Meath</title>\n"; 
echo "\n"; 
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"; 
echo "<meta name=\"description\" content=\"Plumbing and heating services, boiler repairs, replacement and installation, bathroom refit and solar panels servicing Dublin and Meath\">\n"; 
echo "<meta name=\"keywords\" content=\"plumber, central heating, bathroom fitting, emergency plumber, gas boiler services, Meath, Dublin\">\n"; 
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"; 
echo "<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"images/favicon.png\" />\n"; 
echo "		\n"; 
echo "<!--[if lt IE 9]>\n"; 
echo "  <script src=\"//html5shim.googlecode.com/svn/trunk/html5.js\"></script>\n"; 
echo "<![endif]-->\n"; 
echo "        \n"; 
echo "<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" id=\"font_css\" href=\"http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700,300italic,400italic,500italic,700italic|Oswald:400,300,700\">\n"; 
echo "<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" id=\"icon_fontawesome_css\"  href=\"css/font-awesome.css\">\n"; 
echo "<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" id=\"icon_icomoon_css\"  href=\"css/icomoon.css\">\n"; 
echo "<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" id=\"main_css\" href=\"css/style.css\">\n"; 
echo "<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" id=\"responsive_css\" href=\"css/responsive.css\">\n"; 
echo "\n"; 
echo "<script src=\"http://use.edgefonts.net/ubuntu:n4,i4,n7,i7,n3,i3,n5,i5:all.js\"></script>\n"; 
echo "    \n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body>\n"; 
echo "\n"; 
echo "	<footer>\n"; 
echo "		<div id=\"footer_clients\">\n"; 
echo "			<div class=\"container clearfix\">\n"; 
echo "				<div class=\"fifth client\"><img src=\"images/RGI.jpg\" alt=\"Registered Gas Installers\"></div>\n"; 
echo "				<div class=\"fifth client\"><img src=\"images/SEAI_Logo.png\" alt=\"SEAI Logo\"></div>\n"; 
echo "				<div class=\"fifth client\"><img src=\"images/m_logo.jpg\" alt=\"O'Connor Plumbing\"></div>\n"; 
echo "				<div class=\"fifth client\"><img src=\"images/aphci.png\" alt=\"APHCI Logo\"></div>\n"; 
echo "				<div class=\"fifth client\"><img src=\"images/FETAC-Logo.png\" alt=\"Fetac Logo\"></div>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "		<div id=\"footer_columns\">\n"; 
echo "			<div class=\"container\">\n"; 
echo "				<div class=\"row\">\n"; 
echo "					<div class=\"span4\">\n"; 
echo "						<h4>Contact information</h4>\n"; 
echo "						<p>\n"; 
echo "							<strong class=\"blue\">Address:</strong> 4 Bective Park<br>\n"; 
echo "							Kilmessan, Co. Meath<br>\n"; 
echo "							<strong class=\"blue\">Mobile: </strong><a class=\"blue\" href=\"tel:+353 86 809 7792\">+353 86 809 7792</a><br>\n"; 
echo "							<strong class=\"blue\">Email: </strong> <a class=\"blue\" href=\"mailto:info@oconnorplumbing.ie\">info@oconnorplumbing.ie</a><br>\n"; 
echo "						</p>\n"; 
echo "\n"; 
echo "					</div>\n"; 
echo "					<div class=\"span4\">\n"; 
echo "						<h4>Registered Gas Installer</h4>\n"; 
echo "						<p>\n"; 
echo "							Lorem ipsum dolor sit amet, consectetur adng\n"; 
echo "							elit. Donec et diam ac quam intedum vestibler\n"; 
echo "							pulvinar. Pellentesque sodales varius mssa\n"; 
echo "							vitae fauciusis mattis eu. Fusce ante turis\n"; 
echo "						</p>\n"; 
echo "						\n"; 
echo "					</div>\n"; 
echo "					\n"; 
echo "                    <div class=\"span4\">\n"; 
echo "						<h4>SEAI Grants Available</h4>\n"; 
echo "						<p>\n"; 
echo "							Did you know you can now get money back on a new boiler and new central heating installation? <a href=\"contact.html\">Contact us</a> now for more information.\n"; 
echo "						</p>\n"; 
echo "						\n"; 
echo "					</div>\n"; 
echo "                    \n"; 
echo "				</div>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "		<div id=\"footer_copyright\">\n"; 
echo "			<div class=\"container\">\n"; 
echo "				<div class=\"row\">\n"; 
echo "					<div class=\"span8 copyright\">\n"; 
echo "						© 2015 O'Connor Plumbing and Heating | Site by <a href=\"http://www.daraoconnor.com\" target=\"_blank\">Dara O'Connor</a>\n"; 
echo "					</div>\n"; 
echo "				</div>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "	</footer>\n"; 
echo "\n"; 
echo "	\n"; 
echo "\n"; 
echo "\n"; 
echo "	<script src=\"http://maps.google.com/maps/api/js?sensor=false\"></script>\n"; 
echo "	<script type='text/javascript' src='js/jquery-1.9.1.min.js'></script>\n"; 
echo "	<script type='text/javascript' src='js/jquery.roundabout.min.js'></script>\n"; 
echo "	<script type='text/javascript' src='js/jquery.event.drag-2.2.js'></script>\n"; 
echo "	<script type='text/javascript' src='js/jquery.event.drop-2.2.js'></script>\n"; 
echo "	<script type='text/javascript' src='js/jquery.inview.min.js'></script>\n"; 
echo "	<script type='text/javascript' src=\"js/jquery.gmap.min.js\"></script>\n"; 
echo "	<script type='text/javascript' src=\"js/jquery.placeholder.min.js\"></script>\n"; 
echo "	<script type='text/javascript' src='js/superfish.js'></script>\n"; 
echo "	<script type='text/javascript' src='js/custom.js'></script>\n"; 
echo "\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>