<?php
echo "<!DOCTYPE html>\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title>O'Connor Plumbing and Heating, Dublin &amp; Meath</title>\n"; 
echo "\n"; 
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"; 
echo "<meta name=\"description\" content=\"Plumbing and heating services, boiler repairs, replacement and installation, bathroom refit and solar panels servicing Dublin and Meath\">\n"; 
echo "<meta name=\"keywords\" content=\"plumber, central heating, bathroom fitting, emergency plumber, gas boiler services, Meath, Dublin\">\n"; 
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"; 
echo "<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"images/favicon.png\" />\n"; 
echo "		\n"; 
echo "<!--[if lt IE 9]>\n"; 
echo "  <script src=\"//html5shim.googlecode.com/svn/trunk/html5.js\"></script>\n"; 
echo "<![endif]-->\n"; 
echo "        \n"; 
echo "<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" id=\"font_css\" href=\"http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700,300italic,400italic,500italic,700italic|Oswald:400,300,700\">\n"; 
echo "<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" id=\"icon_fontawesome_css\"  href=\"css/font-awesome.css\">\n"; 
echo "<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" id=\"icon_icomoon_css\"  href=\"css/icomoon.css\">\n"; 
echo "<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" id=\"main_css\" href=\"css/style.css\">\n"; 
echo "<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" id=\"responsive_css\" href=\"css/responsive.css\">\n"; 
echo "\n"; 
echo "<script src=\"http://use.edgefonts.net/ubuntu:n4,i4,n7,i7,n3,i3,n5,i5:all.js\"></script>\n"; 
echo "    \n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body>\n"; 
echo "\n"; 
echo "	<header>\n"; 
echo "		<div id=\"menu_bar\">\n"; 
echo "			<div class=\"container\">\n"; 
echo "				<div class=\"row\">\n"; 
echo "					<div class=\"span4\">\n"; 
echo "						<img src=\"images/logo.png\" alt=\"\">\n"; 
echo "					</div>\n"; 
echo "					<div class=\"span8\">\n"; 
echo "						<ul id=\"main_menu\">\n"; 
echo "							<li class=\"current_menu_ancestor\"><a href=\"index.html\"><i class=\"icomoon-home\"></i>Home</a></li>\n"; 
echo "							<li><a href=\"services.html\"><i class=\"icomoon-list\"></i>Services</a></li>\n"; 
echo "							<li><a href=\"testimonials.html\"><i class=\"icomoon-bubbles\"></i>Testimonials</a></li>\n"; 
echo "							<li><a href=\"contact.html\"><i class=\"icomoon-envelop\"></i>Contact</a></li>\n"; 
echo "						</ul>\n"; 
echo "						<select name=\"main_menu_select\" id=\"main_menu_select\">\n"; 
echo "							<option value=\"index.html\" selected>Home</option>\n"; 
echo "							<option value=\"services.html\">Services</option>\n"; 
echo "							<option value=\"testimonials.html\">Testimonials</option>\n"; 
echo "							<option value=\"contact.html\">Contact</option>\n"; 
echo "						</select>\n"; 
echo "					</div>\n"; 
echo "				</div>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "	</header>\n"; 
echo "\n"; 
echo "	\n"; 
echo "\n"; 
echo "\n"; 
echo "	<script src=\"http://maps.google.com/maps/api/js?sensor=false\"></script>\n"; 
echo "	<script type='text/javascript' src='js/jquery-1.9.1.min.js'></script>\n"; 
echo "	<script type='text/javascript' src='js/jquery.roundabout.min.js'></script>\n"; 
echo "	<script type='text/javascript' src='js/jquery.event.drag-2.2.js'></script>\n"; 
echo "	<script type='text/javascript' src='js/jquery.event.drop-2.2.js'></script>\n"; 
echo "	<script type='text/javascript' src='js/jquery.inview.min.js'></script>\n"; 
echo "	<script type='text/javascript' src=\"js/jquery.gmap.min.js\"></script>\n"; 
echo "	<script type='text/javascript' src=\"js/jquery.placeholder.min.js\"></script>\n"; 
echo "	<script type='text/javascript' src='js/superfish.js'></script>\n"; 
echo "	<script type='text/javascript' src='js/custom.js'></script>\n"; 
echo "\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>